name: ANGLE

on:
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        arch: ["arm64"]
      fail-fast: false

    name: "Build for Android ${{matrix.arch}}"
    runs-on: ubuntu-latest

    steps:
      - name: Cache depot_tools
        id: cache-depot-tools
        uses: actions/cache@main
        with:
          path: depot_tools
          key: ${{ runner.os }}-depot-tools-1

      - name: Get ANGLE (shallow clone)
        uses: actions/checkout@main
        with:
          path: 'angle'
          fetch-depth: 1

      - name: Get depot_tools if not cached
        if: steps.cache-depot-tools.outputs.cache-hit != 'true'
        shell: bash
        run: |
          git clone --depth 1 https://chromium.googlesource.com/chromium/tools/depot_tools.git

      - name: Set up environment and build
        shell: bash
        run: |
          export PATH=`pwd`/depot_tools:$PATH
          cd angle
          
          # 仅同步必要的依赖（跳过bootstrap.py，因为配置已存在）
          gclient sync --no-history --shallow --reset
          
          # 直接构建，跳过gn gen步骤
          autoninja -C out/Android-${{matrix.arch}} -j $(nproc)

      - name: Upload ANGLE artifacts
        uses: actions/upload-artifact@main
        with:
          name: angle-libs-${{matrix.arch}}
          path: |
            angle/out/Android-${{matrix.arch}}/libGLESv2_angle.so
            angle/out/Android-${{matrix.arch}}/libEGL_angle.so
