name: ANGLE

on:
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        arch: ["arm64"]
      fail-fast: false

    name: "Build for Android ${{matrix.arch}}"
    runs-on: ubuntu-latest

    steps:

      - name: Cache depot_tools and dependencies
        uses: actions/cache@main
        with:
          path: |
            depot_tools
            angle/third_party
            angle/.cipd
          key: ${{ runner.os }}-angle-deps-${{ hashFiles('angle/DEPS') }}

      - name: Get ANGLE (shallow clone)
        uses: actions/checkout@main
        with:
          path: 'angle'
          fetch-depth: 1
        
      - name: Setup depot_tools
        if: steps.cache-deps.outputs.cache-hit != 'true'
        run: |
          git clone --depth 1 https://chromium.googlesource.com/chromium/tools/depot_tools.git
          echo "DEPOT_TOOLS_COMMIT=$(git -C depot_tools rev-parse HEAD)" >> $GITHUB_ENV

      - name: Run gclient sync (cached)
        run: |
          export PATH=`pwd`/depot_tools:$PATH
          echo $PATH
          cd angle
          echo 'solutions = [{"name": ".", "url": "file://$PWD"}]' > .gclient
          gclient sync --no-history --shallow --reset --force

      - name: Build ANGLE
        env:
          PATH: ${{ github.workspace }}/depot_tools:$PATH
        run: |
          cd angle
          # 使用现有配置直接构建
          autoninja -C out/Android-${{matrix.arch}} -j $(nproc)

      - name: Upload artifacts
        uses: actions/upload-artifact@main
        with:
          name: angle-${{matrix.arch}}-${{ github.run_number }}
          path: angle/out/Android-${{matrix.arch}}/*.so
